#!/bin/bash
#
# Server Scripts Installer
# One-line installer for all server management scripts
#
# Usage: curl -sSL https://raw.githubusercontent.com/7StyleNetOrg/server-scripts/main/setup.sh | sudo bash
#

set -e

# ═══════════════════════════════════════════════════════════════
# CONFIG
# ═══════════════════════════════════════════════════════════════
REPO_URL="https://raw.githubusercontent.com/7StyleNetOrg/server-scripts/main"
INSTALL_DIR="/opt/server-scripts"
VERSION="1.0.1"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ═══════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════

# Read from /dev/tty to support curl | bash
ask() {
    read -p "$1" "$2" < /dev/tty
}

print_banner() {
    clear
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                                                               ║"
    echo "║     ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗          ║"
    echo "║     ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗         ║"
    echo "║     ███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝         ║"
    echo "║     ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗         ║"
    echo "║     ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║         ║"
    echo "║     ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝         ║"
    echo "║                                                               ║"
    echo "║              SERVER SCRIPTS INSTALLER v${VERSION}                 ║"
    echo "║                  github.com/7StyleNetOrg                      ║"
    echo "║                                                               ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[!]${NC} $1"; }
log_error() { echo -e "${RED}[✗]${NC} $1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root!"
        echo "Usage: curl -sSL ${REPO_URL}/setup.sh | sudo bash"
        exit 1
    fi
}

check_dependencies() {
    local missing=()

    for cmd in curl; do
        if ! command -v $cmd &> /dev/null; then
            missing+=($cmd)
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        log_info "Installing dependencies: ${missing[*]}"
        apt update -y > /dev/null 2>&1
        apt install -y ${missing[*]} > /dev/null 2>&1
    fi
}

# ═══════════════════════════════════════════════════════════════
# SCRIPT INSTALLERS
# ═══════════════════════════════════════════════════════════════

install_docker_cleanup() {
    echo ""
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  Docker Cleanup Script Setup${NC}"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    # Get server name
    ask "Server name (e.g., PROD-01) [$(hostname)]: " SERVER_NAME
    SERVER_NAME=${SERVER_NAME:-$(hostname)}

    # Get Slack webhook
    echo ""
    echo -e "${BLUE}To get a Slack Webhook URL:${NC}"
    echo "  1. Go to https://api.slack.com/apps"
    echo "  2. Create/select an app → Incoming Webhooks → Add"
    echo "  3. Copy the webhook URL"
    echo ""
    ask "Slack Webhook URL (Enter to skip): " SLACK_WEBHOOK

    # Get disk threshold
    echo ""
    ask "Disk warning threshold % [80]: " DISK_THRESHOLD
    DISK_THRESHOLD=${DISK_THRESHOLD:-80}

    # Enable prune
    ask "Enable automatic docker prune? [Y/n]: " ENABLE_PRUNE
    ENABLE_PRUNE=${ENABLE_PRUNE:-y}
    [[ "$ENABLE_PRUNE" =~ ^[Yy]$ ]] && ENABLE_PRUNE="true" || ENABLE_PRUNE="false"

    # Create config first
    echo ""
    log_info "Creating configuration..."
    cat > /etc/docker-cleanup.conf << EOF
# Docker Cleanup Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

SLACK_WEBHOOK="${SLACK_WEBHOOK}"
SERVER_NAME="${SERVER_NAME}"
DISK_THRESHOLD=${DISK_THRESHOLD}
ENABLE_PRUNE=${ENABLE_PRUNE}
EOF
    chmod 600 /etc/docker-cleanup.conf
    log_success "Config saved: /etc/docker-cleanup.conf"

    # Download script
    log_info "Downloading docker-cleanup.sh..."
    curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/docker-cleanup.sh" -o "${INSTALL_DIR}/docker-cleanup.sh"
    chmod +x "${INSTALL_DIR}/docker-cleanup.sh"
    log_success "Installed: ${INSTALL_DIR}/docker-cleanup.sh"

    # Create symlink
    ln -sf "${INSTALL_DIR}/docker-cleanup.sh" /usr/local/bin/docker-cleanup
    log_success "Command available: docker-cleanup"

    # Ask to run now
    echo ""
    ask "Run cleanup now? [Y/n]: " RUN_NOW
    RUN_NOW=${RUN_NOW:-y}
    if [[ "$RUN_NOW" =~ ^[Yy]$ ]]; then
        echo ""
        ${INSTALL_DIR}/docker-cleanup.sh
    fi

    echo ""
    log_success "Docker Cleanup installed successfully!"
    echo ""
    echo -e "  ${CYAN}Commands:${NC}"
    echo "    docker-cleanup          Run cleanup"
    echo "    docker-cleanup --setup  Reconfigure"
    echo ""
}

install_server_security() {
    echo ""
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  Server Security Script${NC}"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    log_warning "This will install: UFW, fail2ban, auto-updates, kernel hardening"
    echo ""
    ask "Continue? [Y/n]: " CONFIRM
    CONFIRM=${CONFIRM:-y}

    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        log_info "Skipped."
        return
    fi

    # Download and run
    log_info "Downloading server-security.sh..."
    curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/server-security.sh" -o "${INSTALL_DIR}/server-security.sh"
    chmod +x "${INSTALL_DIR}/server-security.sh"
    log_success "Downloaded: ${INSTALL_DIR}/server-security.sh"

    echo ""
    log_info "Running server security..."
    ${INSTALL_DIR}/server-security.sh

    log_success "Server Security completed!"
}

install_ssl_manager() {
    echo ""
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  SSL Domain Manager${NC}"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    # Download script
    log_info "Downloading ssl-domain-manager.sh..."
    curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/ssl-domain-manager.sh" -o "${INSTALL_DIR}/ssl-domain-manager.sh"
    chmod +x "${INSTALL_DIR}/ssl-domain-manager.sh"
    log_success "Installed: ${INSTALL_DIR}/ssl-domain-manager.sh"

    # Create symlink
    ln -sf "${INSTALL_DIR}/ssl-domain-manager.sh" /usr/local/bin/ssl-manager
    log_success "Command available: ssl-manager"

    # Ask for domain
    echo ""
    ask "Setup a domain now? [y/N]: " SETUP_DOMAIN
    SETUP_DOMAIN=${SETUP_DOMAIN:-n}

    if [[ "$SETUP_DOMAIN" =~ ^[Yy]$ ]]; then
        ask "Enter domain (e.g., example.com): " DOMAIN
        if [[ -n "$DOMAIN" ]]; then
            ${INSTALL_DIR}/ssl-domain-manager.sh "$DOMAIN"
        fi
    fi

    echo ""
    log_success "SSL Manager installed!"
    echo ""
    echo -e "  ${CYAN}Usage:${NC}"
    echo "    ssl-manager example.com"
    echo "    ssl-manager example.com www.example.com"
    echo ""
}

install_all() {
    install_docker_cleanup
    install_server_security
    install_ssl_manager
}

# ═══════════════════════════════════════════════════════════════
# SELF UPDATE
# ═══════════════════════════════════════════════════════════════

self_update() {
    echo ""
    log_info "Checking for updates..."

    local REMOTE_VERSION=$(curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/setup.sh" 2>/dev/null | grep '^VERSION=' | cut -d'"' -f2)

    if [[ -z "$REMOTE_VERSION" ]]; then
        log_error "Could not check for updates"
        return 1
    fi

    if [[ "$REMOTE_VERSION" != "$VERSION" ]]; then
        log_info "New version available: $REMOTE_VERSION (current: $VERSION)"
        ask "Update now? [Y/n]: " UPDATE
        UPDATE=${UPDATE:-y}

        if [[ "$UPDATE" =~ ^[Yy]$ ]]; then
            log_info "Updating..."
            curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/setup.sh" -o "${INSTALL_DIR}/setup.sh"
            chmod +x "${INSTALL_DIR}/setup.sh"
            log_success "Updated! Restarting..."
            exec "${INSTALL_DIR}/setup.sh"
        fi
    else
        log_success "Already up to date (v${VERSION})"
    fi
}

update_scripts() {
    echo ""
    log_info "Updating all installed scripts..."

    local scripts=("docker-cleanup.sh" "server-security.sh" "ssl-domain-manager.sh" "setup.sh")

    for script in "${scripts[@]}"; do
        if [[ -f "${INSTALL_DIR}/${script}" ]]; then
            log_info "Updating ${script}..."
            curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/${script}" -o "${INSTALL_DIR}/${script}"
            chmod +x "${INSTALL_DIR}/${script}"
            log_success "${script} updated"
        fi
    done

    echo ""
    log_success "All scripts updated!"
}

# ═══════════════════════════════════════════════════════════════
# MAIN MENU
# ═══════════════════════════════════════════════════════════════

show_menu() {
    echo ""
    echo -e "${BOLD}Select an option:${NC}"
    echo ""
    echo -e "  ${CYAN}1)${NC} Docker Cleanup      - Auto cleanup + Slack reports"
    echo -e "  ${CYAN}2)${NC} Server Security     - UFW, fail2ban, auto-updates"
    echo -e "  ${CYAN}3)${NC} SSL Domain Manager  - Nginx + Let's Encrypt"
    echo ""
    echo -e "  ${CYAN}4)${NC} Install All"
    echo ""
    echo -e "  ${CYAN}u)${NC} Update all scripts"
    echo -e "  ${CYAN}q)${NC} Quit"
    echo ""
}

main() {
    print_banner
    check_root
    check_dependencies

    # Create install directory
    mkdir -p "$INSTALL_DIR"

    # Save setup.sh itself
    if [[ ! -f "${INSTALL_DIR}/setup.sh" ]]; then
        curl -sSL -H 'Cache-Control: no-cache, no-store' "${REPO_URL}/setup.sh" -o "${INSTALL_DIR}/setup.sh"
        chmod +x "${INSTALL_DIR}/setup.sh"
        ln -sf "${INSTALL_DIR}/setup.sh" /usr/local/bin/server-scripts
        log_success "Installer saved. Run 'server-scripts' anytime."
    fi

    while true; do
        show_menu
        ask "Enter choice [1-4, u, q]: " choice

        case $choice in
            1) install_docker_cleanup ;;
            2) install_server_security ;;
            3) install_ssl_manager ;;
            4) install_all ;;
            u|U) update_scripts ;;
            q|Q)
                echo ""
                log_success "Goodbye!"
                echo ""
                exit 0
                ;;
            *)
                log_warning "Invalid option. Please try again."
                ;;
        esac

        echo ""
        ask "Press Enter to continue..." _
        print_banner
    done
}

# Run
main "$@"
